# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}


{% if item.env is defined %}
{% for var, value in item.env.iteritems() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v dnf-3) ]; then dnf makecache \
      && dnf config-manager --set-disabled Default* \
      && dnf config-manager --set-disabled ubi* \
      && dnf config-manager --set-enabled rhel* \
        --set-enabled ansible* \
      && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf \
      && dnf clean all \
      && dnf --assumeyes install python36 sudo bash rsyslog cronie wget ksh net-tools; \
    elif [ $(command -v yum) ]; then yum makecache fast \
      && yum-config-manager --disable Default* \
      && OS_RELEASE=$(awk '{match($0, /[0-9]+/,version)}END{print version[0]}' /etc/system-release) \
      && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf \
      && yum clean all \
      && yum install -y python sudo yum-plugin-ovl bash rsyslog cronie ksh ca-certificates wget net-tools; \
    fi

RUN echo "XXX" > /.designator
RUN mkdir -p /etc/ansible/facts.d
RUN update-ca-trust enable
RUN wget XXX.crt -P /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust extract

CMD ["init"]
